In [1]:
import numpy as np

# Problem 1

In [2]:
# Define matrix A
A = np.matrix([[3, 5, 9], [3, 3, 4], [5, 9, 17]])

In [3]:
# Define matrix B
B = np.matrix([[2], [1], [4]])

In [4]:
# Solve the matrix equation Ax = B
x = np.linalg.solve(A, B)

In [5]:
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Solution for x:\n", x)

Matrix A:
 [[ 3  5  9]
 [ 3  3  4]
 [ 5  9 17]]
Matrix B:
 [[2]
 [1]
 [4]]
Solution for x:
 [[ 1.]
 [-2.]
 [ 1.]]


# Problem 2

In [ ]:
#We can add the two arrays using the "+" operator in NumPy and then calculate the square of each element using the "**" operator.

In [6]:
# Define arrayOne
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])

# Define arrayTwo
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

In [7]:
# Add the two arrays
resultArray = arrayOne + arrayTwo

In [8]:
# Square each element in the result array
resultArray = resultArray ** 2

In [9]:
print("Array One:\n", arrayOne)
print("Array Two:\n", arrayTwo)
print("Result Array:\n", resultArray)

Array One:
 [[ 5  6  9]
 [21 18 27]]
Array Two:
 [[15 33 24]
 [ 4  7  1]]
Result Array:
 [[ 400 1521 1089]
 [ 625  625  784]]


# Problem 3

In [10]:
# Define the 2-D array
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

In [11]:
# Find the maximum along axis 0
maxAxis0 = np.amax(sampleArray, axis=0)

In [12]:
# Find the minimum along axis 1
minAxis1 = np.amin(sampleArray, axis=1)

In [13]:
print("Sample Array:\n", sampleArray)
print("Maximum along axis 0:\n", maxAxis0)
print("Minimum along axis 1:\n", minAxis1)

Sample Array:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Maximum along axis 0:
 [82 94 73]
Minimum along axis 1:
 [34 12 53]


# Problem 4

In [14]:
# Define the input arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [15]:
# Find the positions where elements of a and b match
matchPositions = np.where(a == b)[0]

In [16]:
print("a:\n", a)
print("b:\n", b)
print("Match Positions:\n", matchPositions)

a:
 [1 2 3 2 3 4 3 4 5 6]
b:
 [ 7  2 10  2  7  4  9  4  9  8]
Match Positions:
 [1 3 5 7]


# Problem 5

In [17]:
# Define the matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [19]:
# Vertically stack the matrices
c = np.vstack((a, b))

In [20]:
print("Matrix a:\n", a)
print("Matrix b:\n", b)
print("Matrix c:\n", c)

Matrix a:
 [[1 2]
 [3 4]]
Matrix b:
 [[5 6]
 [7 8]]
Matrix c:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
# Define the matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [22]:
# Horizontally stack the matrices
d = np.hstack((a, b))

In [23]:
print("Matrix a:\n", a)
print("Matrix b:\n", b)
print("Matrix d:\n", d)


Matrix a:
 [[1 2]
 [3 4]]
Matrix b:
 [[5 6]
 [7 8]]
Matrix d:
 [[1 2 5 6]
 [3 4 7 8]]
